server:
  port: 8085

spring:
  application:
    name: building-object
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/nuthatch_db
    username: nuthatch_user
    password: secret_password
    driver-class-name: org.postgresql.Driver
