server:
  port: 8087

spring:
  application:
    name: documentation-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/nuthatch_db
    username: nuthatch_user
    password: secret_password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

document:
  service:
    aws-access-key-id: accessKeyId
    aws-secret-access-key: secretKey
    aws-region: ru-central1
    aws-uri: https://storage.yandexcloud.net
    aws-bucket: awsBucket
